/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useState, useRef } from 'react';
import { Canvas, useFrame } from '@react-three/fiber';
import { OrbitControls, useGLTF } from '@react-three/drei';
import * as THREE from 'three';
import styled from 'styled-components';

const ModelContainer = styled.div`
  position: absolute;
  width: 100%;
  height: 100%;
  top: calc(50% + 122px);
  left: 50%;
  transform: translate(-50%, -50%);
  z-index: 1;
  opacity: ${({ show }) => (show ? 1 : 0)};
  transition: opacity 1s ease-in-out;
`;

function Model({ onModelClick, scale, modelPath, position = [0, 0, 0], ...props }) {
  console.log('Loading finger model:', modelPath);
  
  const groupRef = useRef();
  const [modelReady, setModelReady] = useState(false);
  
  // Clear specific model from cache
  useEffect(() => {
    // Clear all GLTF cache and preload the new model
    useGLTF.clear();
    // Force browser to not use cache
    const cleanPath = modelPath.split('?')[0];
    useGLTF.preload(cleanPath);
  }, [modelPath]);
  
  const { scene } = useGLTF(modelPath);
  const [hovered, setHovered] = useState(false);
  
  // Auto rotation + allow user to control with mouse
  useFrame((state, delta) => {
    if (groupRef.current) {
      // Keep position fixed
      groupRef.current.position.set(0, 0, 0);
      
      // Continuous rotation in one direction (left)
      groupRef.current.rotation.y += delta * 0.5;
    }
  });
  
  useEffect(() => {
    console.log('Finger model loaded successfully:', modelPath, scene);
    if (scene) {
      console.log('Scene children:', scene.children);
      
      // Calculate the actual geometric center based on vertices
      let totalVertices = 0;
      const vertexSum = new THREE.Vector3(0, 0, 0);
      
      scene.traverse((child) => {
        if (child.isMesh && child.geometry) {
          const geometry = child.geometry;
          
          // Get position attribute
          const positionAttribute = geometry.attributes.position;
          
          if (positionAttribute) {
            const vertices = positionAttribute.array;
            const vertexCount = positionAttribute.count;
            
            // Apply the child's world matrix to get world positions
            child.updateMatrixWorld(true);
            const worldMatrix = child.matrixWorld;
            
            // Sum all vertex positions in world space
            for (let i = 0; i < vertexCount; i++) {
              const vertex = new THREE.Vector3(
                vertices[i * 3],
                vertices[i * 3 + 1], 
                vertices[i * 3 + 2]
              );
              
              // Transform to world space
              vertex.applyMatrix4(worldMatrix);
              vertexSum.add(vertex);
              totalVertices++;
            }
            
            console.log(`Mesh "${child.name}" has ${vertexCount} vertices`);
          }
        }
      });
      
      if (totalVertices > 0) {
        // Calculate the true geometric center
        const geometricCenter = vertexSum.divideScalar(totalVertices);
        
        // Move the entire scene so the geometric center is at origin
        scene.position.set(-geometricCenter.x, -geometricCenter.y, -geometricCenter.z);
        
        console.log('True geometric center:', geometricCenter);
        console.log('Scene positioned at:', scene.position);
        console.log('Total vertices analyzed:', totalVertices);
      } else {
        // Fallback to bounding box if no vertices found
        const box = new THREE.Box3().setFromObject(scene);
        const center = box.getCenter(new THREE.Vector3());
        scene.position.set(-center.x, -center.y, -center.z);
        console.log('Fallback to bounding box center:', center);
      }
      
      // Mark model as ready after centering is complete
      setTimeout(() => {
        setModelReady(true);
      }, 100);
    }
  }, [scene, modelPath]);

  useEffect(() => {
    document.body.style.cursor = hovered ? 'pointer' : 'auto';
  }, [hovered]);

  const handleClick = (e) => {
    e.stopPropagation();
    if (onModelClick) {
      onModelClick();
    }
  };

  // Don't render until model is ready and properly centered
  if (!modelReady) {
    return null;
  }

  return (
    <group ref={groupRef} position={[0, 0, 0]}>
      <group position={position}>
        <primitive
          object={scene}
          scale={hovered ? scale * 1.05 : scale}
          position={[0, 0, 0]}
          rotation={[0, 0, 0]}
          onPointerOver={(e) => { e.stopPropagation(); setHovered(true); }}
          onPointerOut={(e) => { e.stopPropagation(); setHovered(false); }}
          onClick={handleClick}
          {...props}
        />
      </group>
    </group>
  );
}

export default function FingerModelView({ onModelClick, modelPath = '/finger23.glb' }) {
  const [showModel, setShowModel] = useState(false);
  
  // Clear cache and preload the specific model
  useEffect(() => {
    useGLTF.clear();
    useGLTF.preload(modelPath);
    
    // Show model after a short delay for smooth loading
    const timer = setTimeout(() => {
      setShowModel(true);
    }, 200);
    
    return () => clearTimeout(timer);
  }, [modelPath]);
  
  // Finger-specific scale
  const getModelScale = () => {
    return 0.0626373; // Reduced by 0.1 (0.069597 * 0.9)
  };
  
  // Finger-specific position - moved down 45px from previous position
  const getModelPosition = () => {
    return [0, -0.33, 0]; // Move finger23 down by 45px (approximately -1.5 units from 1.17)
  };
  
  return (
    <ModelContainer show={showModel}>
      <Canvas camera={{ position: [0, 12, 7], fov: 45 }}>
        <ambientLight intensity={1.5} />
        <directionalLight position={[10, 10, 5]} intensity={2} />
        <directionalLight position={[-10, -10, -5]} intensity={1} />
        <Model onModelClick={onModelClick} scale={getModelScale()} position={getModelPosition()} modelPath={modelPath} />
        <OrbitControls 
          enableZoom={false} 
          enableRotate={true}
          enablePan={false}
          rotateSpeed={1.0}
        />
      </Canvas>
    </ModelContainer>
  );
} 