/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useState, useRef } from 'react';
import { Canvas, useFrame } from '@react-three/fiber';
import { OrbitControls, useGLTF } from '@react-three/drei';
import styled from 'styled-components';

const ModelContainer = styled.div`
  position: absolute;
  width: 100%;
  height: 100%;
  top: calc(50% + 100px);
  left: 50%;
  transform: translate(-50%, -50%);
  z-index: 1;
`;

function Model({ onModelClick, scale, modelPath, position = [0, 0, 0], ...props }) {
  console.log('Loading model:', modelPath);
  
  const groupRef = useRef();
  
  // Clear specific model from cache
  useEffect(() => {
    // Clear all GLTF cache and preload the new model
    useGLTF.clear();
    // Force browser to not use cache
    const cleanPath = modelPath.split('?')[0];
    useGLTF.preload(cleanPath);
  }, [modelPath]);
  
  const { scene } = useGLTF(modelPath);
  const [hovered, setHovered] = useState(false);
  
  // Auto rotation animation - rotate only around Y-axis at center
  useFrame((state, delta) => {
    if (groupRef.current) {
      // Rotate around Y-axis at center (0, 0, 0)
      groupRef.current.rotation.y += delta * 0.5;
    }
  });
  
  useEffect(() => {
    console.log('Model loaded successfully:', modelPath, scene);
    if (scene) {
      console.log('Scene children:', scene.children);
      
      // Center the model for proper rotation, especially for wiggle22.glb
      if (modelPath.includes('wiggle22.glb')) {
        // Reset any transforms that might cause drift
        scene.position.set(0, 0, 0);
        scene.rotation.set(0, 0, 0);
        scene.scale.set(1, 1, 1);
        
        // Traverse and center all children
        scene.traverse((child) => {
          if (child.isMesh) {
            // Ensure mesh positions are relative to center
            if (child.geometry.boundingBox) {
              child.geometry.computeBoundingBox();
            }
          }
        });
      }
      
      // Adjust blue part scale for clic22.glb
      if (modelPath.includes('clic22.glb')) {
        scene.traverse((child) => {
          if (child.isMesh && child.material) {
            // Check if the material has a blue color
            if (child.material.color) {
              const color = child.material.color;
              // Check if it's blue-ish (higher blue component than red/green)
              if (color.b > color.r && color.b > color.g && color.b > 0.3) {
                // Scale the blue mesh by 0.81972 (0.891 * 0.92)
                child.scale.multiplyScalar(0.81972);
                console.log('Scaled blue mesh:', child.name, color);
              }
            }
            // Also check by position (if blue part is on top)
            else if (child.position.y > 0.5) {
              child.scale.multiplyScalar(0.81972);
              console.log('Scaled top mesh:', child.name, child.position);
            }
          }
        });
      }
    }
  }, [scene, modelPath]);

  useEffect(() => {
    document.body.style.cursor = hovered ? 'pointer' : 'auto';
  }, [hovered]);

  const handleClick = (e) => {
    e.stopPropagation();
    if (onModelClick) {
      onModelClick();
    }
  };

  // Center the model properly for wiggle22.glb
  const getModelCenterOffset = () => {
    if (modelPath.includes('wiggle22.glb')) {
      return [0, 0, 0]; // Keep centered at origin for proper rotation
    }
    return [0, 0, 0];
  };

  return (
    <group ref={groupRef} position={[0, 0, 0]}>
      <group position={position}>
        <primitive
          object={scene}
          scale={hovered ? scale * 1.05 : scale}
          position={[0, 0, 0]}
          onPointerOver={(e) => { e.stopPropagation(); setHovered(true); }}
          onPointerOut={(e) => { e.stopPropagation(); setHovered(false); }}
          onClick={handleClick}
          {...props}
        />
      </group>
    </group>
  );
}

export default function FlowerModelView({ onModelClick, modelPath = '/flower29.glb' }) {
  // Clear cache and preload the specific model
  useEffect(() => {
    useGLTF.clear();
    useGLTF.preload(modelPath);
  }, [modelPath]);
  
  // Set different scales based on model type
  const getModelScale = () => {
    if (modelPath.includes('wiggle22.glb')) {
      return 0.0788415804; // 7% more increase for wiggle22 (0.07368372 * 1.07)
    }
    if (modelPath.includes('clic22.glb')) {
      return 0.07485544; // 10% more increase for clic22 (0.0680504 * 1.1)
    }
    return 0.07733; // Default scale for other models
  };
  
  // Set different positions based on model type
  const getModelPosition = () => {
    if (modelPath.includes('wiggle22.glb')) {
      return [0.3, -2.4, 0]; // Move wiggle22 down 33px more and right 12px
    }
    if (modelPath.includes('clic22.glb')) {
      return [0, -2.2, 0]; // Move clic22 down by 25px more (total 91px)
    }
    return [0, 0, 0]; // Default position for other models
  };
  
  return (
    <ModelContainer>
      <Canvas camera={{ position: [0, 12, 7], fov: 45 }}>
        <ambientLight intensity={1.5} />
        <directionalLight position={[10, 10, 5]} intensity={2} />
        <directionalLight position={[-10, -10, -5]} intensity={1} />
        <Model onModelClick={onModelClick} scale={getModelScale()} position={getModelPosition()} modelPath={modelPath} />
        <OrbitControls enableZoom={false} />
      </Canvas>
    </ModelContainer>
  );
} 