/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { Suspense } from 'react'
import styled from 'styled-components'
import { Canvas } from '@react-three/fiber'
import { useGLTF, Stage, OrbitControls } from '@react-three/drei'

const ModelContainer = styled.div`
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  width: 100vw;
  height: 100vh;
  z-index: 999;
`;

function Model(props) {
  const { scene } = useGLTF('/Flower27.glb')
  return <primitive object={scene} {...props} />;
}

useGLTF.preload('/Flower27.glb')

export default function FlowerModelView() {
  return (
    <ModelContainer>
      <Canvas dpr={[1, 2]} camera={{ fov: 45 }}>
        <Suspense fallback={null}>
          <Stage environment="city" intensity={0.6}>
            <Model />
          </Stage>
        </Suspense>
        <OrbitControls autoRotate />
      </Canvas>
    </ModelContainer>
  );
} 