/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useState, useRef } from 'react';
import { Canvas, useFrame } from '@react-three/fiber';
import { OrbitControls, useGLTF } from '@react-three/drei';
import styled from 'styled-components';

const ModelContainer = styled.div`
  position: absolute;
  width: 100%;
  height: 100%;
  top: calc(50% + 100px);
  left: 50%;
  transform: translate(-50%, -50%);
  z-index: 1;
`;

function Model({ onModelClick, scale, modelPath, position = [0, 0, 0], ...props }) {
  console.log('Loading model:', modelPath);
  
  const groupRef = useRef();
  
  // Clear specific model from cache
  useEffect(() => {
    // Clear all GLTF cache and preload the new model
    useGLTF.clear();
    // Force browser to not use cache
    const cleanPath = modelPath.split('?')[0];
    useGLTF.preload(cleanPath);
  }, [modelPath]);
  
  const { scene } = useGLTF(modelPath);
  const [hovered, setHovered] = useState(false);
  
  // Auto rotation animation - rotate the group instead of individual model
  useFrame((state, delta) => {
    if (groupRef.current) {
      groupRef.current.rotation.y += delta * 0.5; // Rotate around Y-axis
    }
  });
  
  useEffect(() => {
    console.log('Model loaded successfully:', modelPath, scene);
    if (scene) {
      console.log('Scene children:', scene.children);
    }
  }, [scene, modelPath]);

  useEffect(() => {
    document.body.style.cursor = hovered ? 'pointer' : 'auto';
  }, [hovered]);

  const handleClick = (e) => {
    e.stopPropagation();
    if (onModelClick) {
      onModelClick();
    }
  };

  return (
    <group ref={groupRef} position={position}>
      <primitive
        object={scene}
        scale={hovered ? scale * 1.05 : scale}
        position={[0, 0, 0]}
        onPointerOver={(e) => { e.stopPropagation(); setHovered(true); }}
        onPointerOut={(e) => { e.stopPropagation(); setHovered(false); }}
        onClick={handleClick}
        {...props}
      />
    </group>
  );
}

export default function FlowerModelView({ onModelClick, modelPath = '/flower29.glb' }) {
  // Clear cache and preload the specific model
  useEffect(() => {
    useGLTF.clear();
    useGLTF.preload(modelPath);
  }, [modelPath]);
  
  // Set different scales based on model type
  const getModelScale = () => {
    if (modelPath.includes('wiggle22.glb')) {
      return 0.0788415804; // 7% more increase for wiggle22 (0.07368372 * 1.07)
    }
    return 0.07733; // Default scale for other models
  };
  
  // Set different positions based on model type
  const getModelPosition = () => {
    if (modelPath.includes('wiggle22.glb')) {
      return [0.3, -2.4, 0]; // Move wiggle22 down 33px more and right 12px
    }
    return [0, 0, 0]; // Default position for other models
  };
  
  return (
    <ModelContainer>
      <Canvas camera={{ position: [0, 12, 7], fov: 45 }}>
        <ambientLight intensity={1.5} />
        <directionalLight position={[10, 10, 5]} intensity={2} />
        <directionalLight position={[-10, -10, -5]} intensity={1} />
        <Model onModelClick={onModelClick} scale={getModelScale()} position={getModelPosition()} modelPath={modelPath} />
        <OrbitControls enableZoom={false} />
      </Canvas>
    </ModelContainer>
  );
} 