/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useState, useRef } from 'react';
import { Canvas, useFrame } from '@react-three/fiber';
import { OrbitControls, useGLTF } from '@react-three/drei';
import * as THREE from 'three';
import styled from 'styled-components';

const ModelContainer = styled.div`
  position: absolute;
  width: 100%;
  height: 100%;
  top: calc(50% + 122px);
  left: 50%;
  transform: translate(-50%, -50%);
  z-index: 1;
`;

function Model({ onModelClick, scale, modelPath, position = [0, 0, 0], ...props }) {
  console.log('Loading model:', modelPath);
  
  const groupRef = useRef();
  
  // Clear specific model from cache
  useEffect(() => {
    // Clear all GLTF cache and preload the new model
    useGLTF.clear();
    // Force browser to not use cache
    const cleanPath = modelPath.split('?')[0];
    useGLTF.preload(cleanPath);
  }, [modelPath]);
  
  const { scene } = useGLTF(modelPath);
  const [hovered, setHovered] = useState(false);
  
  // Auto rotation + allow user to control with mouse
  useFrame((state, delta) => {
    if (groupRef.current) {
      // Keep position fixed
      groupRef.current.position.set(0, 0, 0);
      
      // Continuous rotation in one direction (left)
      groupRef.current.rotation.y += delta * 0.5;
    }
  });
  
  useEffect(() => {
    console.log('Model loaded successfully:', modelPath, scene);
    if (scene) {
      console.log('Scene children:', scene.children);
      
      // Calculate bounding box to center the model
      const box = new THREE.Box3().setFromObject(scene);
      const center = box.getCenter(new THREE.Vector3());
      
      // Move the scene so its center is at origin (0,0,0)
      scene.position.set(-center.x, -center.y, -center.z);
      
      // Center the model properly for wiggle22.glb
      if (modelPath.includes('wiggle22.glb')) {
        // Reset any transforms that might cause drift
        scene.rotation.set(0, 0, 0);
        scene.scale.set(1, 1, 1);
        
        // Traverse and center all children
        scene.traverse((child) => {
          if (child.isMesh) {
            // Ensure mesh positions are relative to center
            if (child.geometry.boundingBox) {
              child.geometry.computeBoundingBox();
            }
          }
        });
      }
    }
  }, [scene, modelPath]);

  useEffect(() => {
    document.body.style.cursor = hovered ? 'pointer' : 'auto';
  }, [hovered]);

  const handleClick = (e) => {
    e.stopPropagation();
    if (onModelClick) {
      onModelClick();
    }
  };

  // Center the model properly for wiggle22.glb
  const getModelCenterOffset = () => {
    if (modelPath.includes('wiggle22.glb')) {
      return [0, 0, 0]; // Keep centered at origin for proper rotation
    }
    return [0, 0, 0];
  };

  return (
    <group ref={groupRef} position={[0, 0, 0]}>
      <group position={position}>
        <primitive
          object={scene}
          scale={hovered ? scale * 1.05 : scale}
          position={[0, 0, 0]}
          rotation={[0, 0, 0]}
          onPointerOver={(e) => { e.stopPropagation(); setHovered(true); }}
          onPointerOut={(e) => { e.stopPropagation(); setHovered(false); }}
          onClick={handleClick}
          {...props}
        />
      </group>
    </group>
  );
}

export default function WiggleModelView({ onModelClick, modelPath = '/wiggle22.glb' }) {
  // Clear cache and preload the specific model
  useEffect(() => {
    useGLTF.clear();
    useGLTF.preload(modelPath);
  }, [modelPath]);
  
  // Set different scales based on model type
  const getModelScale = () => {
    if (modelPath.includes('wiggle22.glb')) {
      return 0.0788415804; // 7% more increase for wiggle22 (0.07368372 * 1.07)
    }
    if (modelPath.includes('clic22.glb')) {
      return 0.07841856045; // Reduced by 0.03 (0.08084387552 * 0.97)
    }
    return 0.069597; // Default scale for other models (0.07733 * 0.9)
  };
  
  // Set different positions based on model type
  const getModelPosition = () => {
    if (modelPath.includes('wiggle22.glb')) {
      return [0.3, -0.4, 0]; // Move wiggle22 up 60px from previous position
    }
    if (modelPath.includes('clic22.glb')) {
      return [0, 1.1, 0]; // Move clic22 up by 30px more from previous position
    }
    return [0, 0, 0]; // Default position for other models
  };
  
  return (
    <ModelContainer>
      <Canvas camera={{ position: [0, 12, 7], fov: 45 }}>
        <ambientLight intensity={1.5} />
        <directionalLight position={[10, 10, 5]} intensity={2} />
        <directionalLight position={[-10, -10, -5]} intensity={1} />
        <Model onModelClick={onModelClick} scale={getModelScale()} position={getModelPosition()} modelPath={modelPath} />
        <OrbitControls 
          enableZoom={false} 
          enableRotate={true}
          enablePan={false}
          rotateSpeed={1.0}
        />
      </Canvas>
    </ModelContainer>
  );
} 