/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useState, useRef } from 'react';
import { Canvas, useFrame } from '@react-three/fiber';
import { OrbitControls, useGLTF } from '@react-three/drei';
import * as THREE from 'three';
import styled from 'styled-components';

const ModelContainer = styled.div`
  position: absolute;
  width: 100%;
  height: 100%;
  top: calc(50% + 122px);
  left: 50%;
  transform: translate(-50%, -50%);
  z-index: 1;
  opacity: ${({ show }) => (show ? 1 : 0)};
  transition: opacity 1s ease-in-out;
`;

function Model({ onModelClick, scale, modelPath, position = [0, 0, 0], ...props }) {
  console.log('Loading wiggle model:', modelPath);
  
  const groupRef = useRef();
  const [modelReady, setModelReady] = useState(false);
  
  // Clear specific model from cache
  useEffect(() => {
    // Clear all GLTF cache and preload the new model
    useGLTF.clear();
    // Force browser to not use cache
    const cleanPath = modelPath.split('?')[0];
    useGLTF.preload(cleanPath);
  }, [modelPath]);
  
  const { scene } = useGLTF(modelPath);
  const [hovered, setHovered] = useState(false);
  
  // Auto rotation + allow user to control with mouse
  useFrame((state, delta) => {
    if (groupRef.current) {
      // Keep position fixed
      groupRef.current.position.set(0, 0, 0);
      
      // Continuous rotation in one direction (left)
      groupRef.current.rotation.y += delta * 0.5;
    }
  });
  
    useEffect(() => {
    console.log('Wiggle model loaded successfully:', modelPath, scene);
    if (scene) {
      console.log('Scene children:', scene.children);
      
      // Reset transforms first
      scene.rotation.set(0, 0, 0);
      scene.scale.set(1, 1, 1);
      scene.position.set(0, 0, 0);
      
      // Calculate volume-weighted center for more accurate centering
      let totalVolume = 0;
      const weightedCenter = new THREE.Vector3(0, 0, 0);
      
      scene.traverse((child) => {
        if (child.isMesh && child.geometry) {
          // Force compute bounding box
          child.geometry.computeBoundingBox();
          
          const box = new THREE.Box3().setFromObject(child);
          const meshCenter = box.getCenter(new THREE.Vector3());
          const size = box.getSize(new THREE.Vector3());
          
          // Calculate approximate volume (width * height * depth)
          const volume = size.x * size.y * size.z;
          
          // Weight center by volume
          weightedCenter.add(meshCenter.multiplyScalar(volume));
          totalVolume += volume;
          
          console.log(`Mesh center: ${meshCenter.x}, ${meshCenter.y}, ${meshCenter.z}, volume: ${volume}`);
        }
      });
      
      if (totalVolume > 0) {
        // Calculate volume-weighted center
        const volumeCenter = weightedCenter.divideScalar(totalVolume);
        
        // For wiggle model, manually adjust Y center to be more visual center
        // (assuming the visual center is higher than the geometric center)
        const adjustedCenter = new THREE.Vector3(
          volumeCenter.x,
          volumeCenter.y + 0.3, // Move center point up by 0.3 units to get visual center
          volumeCenter.z
        );
        
        // Move scene to center the visual core
        scene.position.set(-adjustedCenter.x, -adjustedCenter.y, -adjustedCenter.z);
        
        console.log('Volume-weighted center:', volumeCenter);
        console.log('Adjusted center:', adjustedCenter);
        console.log('Scene positioned at:', scene.position);
      }
      
      // Mark model as ready after centering is complete
      setTimeout(() => {
        setModelReady(true);
      }, 100);
    }
  }, [scene, modelPath]);

  useEffect(() => {
    document.body.style.cursor = hovered ? 'pointer' : 'auto';
  }, [hovered]);

  const handleClick = (e) => {
    e.stopPropagation();
    if (onModelClick) {
      onModelClick();
    }
  };

  // Don't render until model is ready and properly centered
  if (!modelReady) {
    return null;
  }

  return (
    <group ref={groupRef} position={[0, 0, 0]}>
      <group position={position}>
        <primitive
          object={scene}
          scale={hovered ? scale * 1.05 : scale}
          position={[0, 0, 0]}
          rotation={[0, 0, 0]}
          onPointerOver={(e) => { e.stopPropagation(); setHovered(true); }}
          onPointerOut={(e) => { e.stopPropagation(); setHovered(false); }}
          onClick={handleClick}
          {...props}
        />
      </group>
    </group>
  );
}

export default function WiggleModelView({ onModelClick, modelPath = '/wiggle22.glb' }) {
  const [showModel, setShowModel] = useState(false);
  
  // Clear cache and preload the specific model
  useEffect(() => {
    useGLTF.clear();
    useGLTF.preload(modelPath);
    
    // Show model after a short delay for smooth loading
    const timer = setTimeout(() => {
      setShowModel(true);
    }, 200);
    
    return () => clearTimeout(timer);
  }, [modelPath]);
  
  // Wiggle-specific scale
  const getModelScale = () => {
    return 0.063861680124; // Reduced by 0.1 more (0.07095742236 * 0.9)
  };
  
  // Wiggle-specific position
  const getModelPosition = () => {
    return [0.3, -0.73, 0]; // Move wiggle22 down 60px from previous position
  };
  
  return (
    <ModelContainer show={showModel}>
      <Canvas camera={{ position: [0, 12, 7], fov: 45 }}>
        <ambientLight intensity={1.5} />
        <directionalLight position={[10, 10, 5]} intensity={2} />
        <directionalLight position={[-10, -10, -5]} intensity={1} />
        <Model onModelClick={onModelClick} scale={getModelScale()} position={getModelPosition()} modelPath={modelPath} />
        <OrbitControls 
          enableZoom={false} 
          enableRotate={true}
          enablePan={false}
          rotateSpeed={1.0}
        />
      </Canvas>
    </ModelContainer>
  );
} 